
name: medi_mind
description: "MediMind: Medication Reminder & Companion."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16
  smooth_page_indicator: ^1.2.0+3
  percent_indicator: ^4.2.4
  input_quantity: ^2.5.0
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  provider: ^6.1.2
  sqflite: ^2.4.1
  path: ^1.9.0
  uuid: ^4.5.1
  fl_chart: ^0.69.2
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: 'Spartan League'
      fonts:
        - asset : assets/fonts/LeagueSpartan-Regular.ttf 
  assets:
    - assets/images/
    - assets/icons/
